site_name: DiscordKt

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences

theme: 
    name: material
    logo: images/discordkt-logo.png
    palette:
        scheme: slate
        primary: cyan
        accent: cyan

nav:
    - index.md
    - Concepts:
        - Commands: 
            - 'concepts/commands/Basics.md'
            - 'concepts/commands/Input.md'
            - 'concepts/commands/Optionals.md'
        - 'concepts/Listeners.md'
        - 'concepts/Services.md'
        - 'concepts/Preconditions.md'
        - 'concepts/Data.md'
    - DSL:
        - 'dsl/Menu.md'
    - Extending:
        - 'extending/Arguments.md'
    - 'API Docs': '/dokka/-discord-kt/index.html'

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/DiscordKt/DiscordKt
        - icon: fontawesome/brands/discord
          link: https://discord.gg/REZVVjA